import { Rethink_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const rethinkSans = Rethink_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-rethink-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da" className={rethinkSans.variable}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
